baseurl = "https://travisgerke.com/"
relativeurls = true
languageCode = "en-US"
title = "Travis Gerke, ScD"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-49177216-1"
theme = "hugo-sustain"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Travis Gerke"
  description = "Website of Travis Gerke, ScD. Focus on molecular epidemiology, biostatistics, computer science, and genetics."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "tgerke"
  Email         = "travisgerke@gmail.com"
  Twitter       = "travisgerke"
  LinkedIn      = "travisgerke"
  GoogleScholar = "mP-fw2gAAAAJ"
  Stackoverflow = "users/7410711/travis-gerke"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "publications"
  identifier = "publications"
  weight = 300
  url = "/publications/"
[[menu.main]]
  name = "CV"
  identifier = "CV"
  weight = 400
  url = "/cv/"
