languageCode = "en-US"
relativeurls = true
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://travisgerke.com/"
googleAnalytics = ""
theme = "hugo-vitae"

[params]
  author = "Travis Gerke"
  title = "Travis Gerke's CV"
  description = "Travis Gerke's Curriculum Vitae"
  avatar = "profile.png"
  email = "travisgerke@gmail.com"
  email_full = "mailto:travisgerke@gmail.com"
  website = "travisgerke.com"
  website_full = "https://travisgerke.com"
  github = "tgerke"
  twitter = "travisgerke"
  tel = "+1 813 745-6448"
  tel_full = "+1 813 745-6448"
  google_maps = "https://www.google.com/maps/place/12902+USF+Magnolia+Drive,+Tampa,+FL+33612/"
  address = "12902 Magnolia Drive"
  postcode = "MRC-219"
  city = "Tampa, FL 33612"
  country = "United States"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
